/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "kawhnqzkbsajoncphwbr"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imthd2hucXprYnNham9uY3Bod2JyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMxNDE2ODEsImV4cCI6MjA3ODcxNzY4MX0.-u2jc8LOWqWnfVr-9QvB2Fwa1J-AHAt0O6KP85mr7FY"